# defair configuration
# holds network rpc endpoints, protocol types, token and contract addresses

networks:
  avalanche:
    endpoint: https://api.avax.network/ext/bc/C/rpc
    tokens:
      wAVAX: 0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7
      JOE: 0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd
      MIM: 0x130966628846BFd36ff31a822705796e8cb8C18D
      TIME: 0xb54f16fb19478766a268f172c9480f8da1a7c9c3
      MEMO: 0x136Acd46C134E8269052c62A67042D6bDeDde3C9
      SB: 0x7d1232B90D3F809A54eeaeeBC639C62dF8a8942f
      sSB: 0xe9eb40d52ce4744322204d4a29af63c30f0260a4
    exchanges:
    - name: Trader Joe
      token: 'JOE'
      controller: 0xdc13687554205E5b89Ac783db14bb5bba4A1eDaC
    markets:
    - name: Trader Joe
      token: 'JOE'
      chef: 0xd6a4f121ca35509af06a0be99093d08462f53052
    rebasers:
    - name: Wonderland
      token: 'TIME'
  harmony:
    endpoint: https://api.harmony.one
  fantom:
    endpoint: https://rpc.ftm.tools
