# defair configuration
# holds network rpc endpoints, protocol types, token and contract addresses

networks:
  avalanche:
    endpoint: https://api.avax.network/ext/bc/C/rpc
    tokens:
      lists:
      - "https://raw.githubusercontent.com/pangolindex/tokenlists/main/ab.tokenlist.json"
      - "https://raw.githubusercontent.com/pangolindex/tokenlists/main/defi.tokenlist.json"
      additional:
      - 0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E # USDC (Native)
      - 0x130966628846BFd36ff31a822705796e8cb8C18D # Magic Internet Money
      - 0x0f34919404a290e71fc6A510cB4a6aCb8D764b24 # Blizz
      - 0x136Acd46C134E8269052c62A67042D6bDeDde3C9 # Memories (Time)
    exchanges:
    - name: Trader Joe
      token: 'JOE'
      controller: 0xdc13687554205E5b89Ac783db14bb5bba4A1eDaC
    markets:
    - name: Trader Joe
      token: 'JOE'
      chef:
      - 0xd6a4f121ca35509af06a0be99093d08462f53052
      - 0x188bED1968b795d5c9022F6a0bb5931Ac4c18F00
    rebasers:
    - name: Wonderland
      token: 'TIME'
  harmony:
    endpoint: https://api.harmony.one
    tokens:
      lists:
      - "https://raw.githubusercontent.com/DefiKingdoms/community-token-list/main/src/defikingdoms-default.tokenlist.json"
    markets:
    - name: Defi Kingdoms
      token: 'JEWEL'
      chef:
      - 0xdb30643c71ac9e2122ca0341ed77d09d5f99f924
  fantom:
    endpoint: https://rpc.ftm.tools
